spring.application.name=wearables

spring.datasource.url=jdbc:postgresql://localhost:5432/wearables
spring.datasource.username=wearables
spring.datasource.password=wearables

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
